-- TABLA RESUMEN DE BATALLA
CREATE TABLE BATTLE_STATS (
    CIVILIZATION_ID NUMBER(10) NOT NULL,
    NUM_BATTLE NUMBER(10) NOT NULL,
    BATTLE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    WOOD_ACQUIRED NUMBER(10), -- Escombros recolectados
    IRON_ACQUIRED NUMBER(10), -- Escombros recolectados
    RESULT VARCHAR2(10),      -- 'WIN' o 'LOST'
    CONSTRAINT PK_BATTLE_STATS PRIMARY KEY (CIVILIZATION_ID, NUM_BATTLE),
    CONSTRAINT FK_BATTLE_CIV FOREIGN KEY (CIVILIZATION_ID) REFERENCES CIVILIZATION_STATS (CIVILIZATION_ID)
);

-- ESTADÍSTICAS DE UNIDADES PROPIAS EN CADA BATALLA (Para el Reporte)
CREATE TABLE CIVILIZATION_BATTLE_UNITS (
    CIVILIZATION_ID NUMBER(10) NOT NULL,
    NUM_BATTLE NUMBER(10) NOT NULL,
    UNIT_TYPE VARCHAR2(50) NOT NULL,
    INITIAL_COUNT NUMBER(10),
    REMAINING_COUNT NUMBER(10),
    CONSTRAINT PK_CIV_BATTLE_UNITS PRIMARY KEY (CIVILIZATION_ID, NUM_BATTLE, UNIT_TYPE),
    CONSTRAINT FK_CBU_BATTLE FOREIGN KEY (CIVILIZATION_ID, NUM_BATTLE) REFERENCES BATTLE_STATS (CIVILIZATION_ID, NUM_BATTLE)
);

-- ESTADÍSTICAS DE UNIDADES ENEMIGAS EN CADA BATALLA
CREATE TABLE ENEMY_BATTLE_UNITS (
    CIVILIZATION_ID NUMBER(10) NOT NULL,
    NUM_BATTLE NUMBER(10) NOT NULL,
    UNIT_TYPE VARCHAR2(50) NOT NULL,
    INITIAL_COUNT NUMBER(10),
    REMAINING_COUNT NUMBER(10),
    CONSTRAINT PK_ENEMY_BATTLE_UNITS PRIMARY KEY (CIVILIZATION_ID, NUM_BATTLE, UNIT_TYPE),
    CONSTRAINT FK_EBU_BATTLE FOREIGN KEY (CIVILIZATION_ID, NUM_BATTLE) REFERENCES BATTLE_STATS (CIVILIZATION_ID, NUM_BATTLE)
);

-- LOG DETALLADO PASO A PASO (Para el Battle Development)
CREATE TABLE BATTLE_LOG (
    CIVILIZATION_ID NUMBER(10) NOT NULL,
    NUM_BATTLE NUMBER(10) NOT NULL,
    LOG_LINE NUMBER(10) NOT NULL,
    LOG_ENTRY VARCHAR2(500), -- Ampliado para las frases de daño y eventos
    CONSTRAINT PK_BATTLE_LOG PRIMARY KEY (CIVILIZATION_ID, NUM_BATTLE, LOG_LINE),
    CONSTRAINT FK_LOG_BATTLE FOREIGN KEY (CIVILIZATION_ID, NUM_BATTLE) REFERENCES BATTLE_STATS (CIVILIZATION_ID, NUM_BATTLE)
);