-- Asegúrate de que tu base de datos esté seleccionada
-- USE nombre_de_tu_base_de_datos;

-- 1. TABLA RESUMEN DE BATALLA
CREATE TABLE BATTLE_STATS (
    CIVILIZATION_ID INT NOT NULL,
    NUM_BATTLE INT NOT NULL,
    BATTLE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    WOOD_ACQUIRED INT, 
    IRON_ACQUIRED INT, 
    RESULT VARCHAR(10),      -- 'WIN' o 'LOST'
    CONSTRAINT PK_BATTLE_STATS PRIMARY KEY (CIVILIZATION_ID, NUM_BATTLE),
    CONSTRAINT FK_BATTLE_CIV FOREIGN KEY (CIVILIZATION_ID) REFERENCES CIVILIZATION_STATS (CIVILIZATION_ID)
);

-- 2. ESTADÍSTICAS DE UNIDADES PROPIAS EN CADA BATALLA
CREATE TABLE CIVILIZATION_BATTLE_UNITS (
    CIVILIZATION_ID INT NOT NULL,
    NUM_BATTLE INT NOT NULL,
    UNIT_TYPE VARCHAR(50) NOT NULL,
    INITIAL_COUNT INT,
    REMAINING_COUNT INT,
    CONSTRAINT PK_CIV_BATTLE_UNITS PRIMARY KEY (CIVILIZATION_ID, NUM_BATTLE, UNIT_TYPE),
    CONSTRAINT FK_CBU_BATTLE FOREIGN KEY (CIVILIZATION_ID, NUM_BATTLE) REFERENCES BATTLE_STATS (CIVILIZATION_ID, NUM_BATTLE)
);

-- 3. ESTADÍSTICAS DE UNIDADES ENEMIGAS EN CADA BATALLA
CREATE TABLE ENEMY_BATTLE_UNITS (
    CIVILIZATION_ID INT NOT NULL,
    NUM_BATTLE INT NOT NULL,
    UNIT_TYPE VARCHAR(50) NOT NULL,
    INITIAL_COUNT INT,
    REMAINING_COUNT INT,
    CONSTRAINT PK_ENEMY_BATTLE_UNITS PRIMARY KEY (CIVILIZATION_ID, NUM_BATTLE, UNIT_TYPE),
    CONSTRAINT FK_EBU_BATTLE FOREIGN KEY (CIVILIZATION_ID, NUM_BATTLE) REFERENCES BATTLE_STATS (CIVILIZATION_ID, NUM_BATTLE)
);

-- 4. LOG DETALLADO PASO A PASO
CREATE TABLE BATTLE_LOG (
    CIVILIZATION_ID INT NOT NULL,
    NUM_BATTLE INT NOT NULL,
    LOG_LINE INT NOT NULL,
    LOG_ENTRY VARCHAR(500), 
    CONSTRAINT PK_BATTLE_LOG PRIMARY KEY (CIVILIZATION_ID, NUM_BATTLE, LOG_LINE),
    CONSTRAINT FK_LOG_BATTLE FOREIGN KEY (CIVILIZATION_ID, NUM_BATTLE) REFERENCES BATTLE_STATS (CIVILIZATION_ID, NUM_BATTLE)
);