-- SECUENCIA PARA IDs DE CIVILIZACIÓN
CREATE SEQUENCE CIVILIZATION_SEQ START WITH 1 INCREMENT BY 1;

-- TABLA DE ESTADO GENERAL (Recursos, Edificios y Tecnologías)
CREATE TABLE CIVILIZATION_STATS (
    CIVILIZATION_ID NUMBER(10) NOT NULL,
    NAME VARCHAR2(50),
    WOOD_AMOUNT NUMBER(10),
    IRON_AMOUNT NUMBER(10),
    FOOD_AMOUNT NUMBER(10),
    MANA_AMOUNT NUMBER(10),
    MAGICTOWER_COUNTER NUMBER(10) DEFAULT 0,
    CHURCH_COUNTER NUMBER(10) DEFAULT 0,
    FARM_COUNTER NUMBER(10) DEFAULT 0,
    SMITHY_COUNTER NUMBER(10) DEFAULT 0,
    CARPENTRY_COUNTER NUMBER(10) DEFAULT 0,
    TECHNOLOGY_DEFENSE_LEVEL NUMBER(10) DEFAULT 0,
    TECHNOLOGY_ATTACK_LEVEL NUMBER(10) DEFAULT 0,
    BATTLES_COUNTER NUMBER(10) DEFAULT 0,
    CONSTRAINT PK_CIVILIZATION_STATS PRIMARY KEY (CIVILIZATION_ID)
);

-- TABLA DE UNIDADES DE ATAQUE
CREATE TABLE ATTACK_UNITS_STATS (
    CIVILIZATION_ID NUMBER(10) NOT NULL,
    UNIT_ID NUMBER(10) NOT NULL,
    TYPE_UNIT VARCHAR2(20),
    ARMOR NUMBER(10),
    BASE_DAMAGE NUMBER(10),
    EXPERIENCE NUMBER(10) DEFAULT 0,
    SANCTIFIED VARCHAR2(3) DEFAULT 'NO',
    CONSTRAINT PK_ATTACK_UNITS PRIMARY KEY (CIVILIZATION_ID, UNIT_ID),
    CONSTRAINT FK_ATTACK_CIV FOREIGN KEY (CIVILIZATION_ID) REFERENCES CIVILIZATION_STATS (CIVILIZATION_ID),
    CONSTRAINT CHK_TYPE_ATTACK CHECK (TYPE_UNIT IN ('Swordsman', 'Spearman', 'Crossbow', 'Cannon'))
);

-- TABLA DE UNIDADES DE DEFENSA
CREATE TABLE DEFENSE_UNITS_STATS (
    CIVILIZATION_ID NUMBER(10) NOT NULL,
    UNIT_ID NUMBER(10) NOT NULL,
    TYPE_UNIT VARCHAR2(30),
    ARMOR NUMBER(10),
    BASE_DAMAGE NUMBER(10),
    EXPERIENCE NUMBER(10) DEFAULT 0,
    SANCTIFIED VARCHAR2(3) DEFAULT 'NO',
    CONSTRAINT PK_DEFENSE_UNITS PRIMARY KEY (CIVILIZATION_ID, UNIT_ID),
    CONSTRAINT FK_DEFENSE_CIV FOREIGN KEY (CIVILIZATION_ID) REFERENCES CIVILIZATION_STATS (CIVILIZATION_ID),
    CONSTRAINT CHK_TYPE_DEFENSE CHECK (TYPE_UNIT IN ('Arrow Tower', 'Catapult', 'Rocket Launcher Tower'))
);

-- TABLA DE UNIDADES ESPECIALES
CREATE TABLE SPECIAL_UNITS_STATS (
    CIVILIZATION_ID NUMBER(10) NOT NULL,
    UNIT_ID NUMBER(10) NOT NULL,
    TYPE_UNIT VARCHAR2(20),
    ARMOR NUMBER(10),
    BASE_DAMAGE NUMBER(10),
    EXPERIENCE NUMBER(10) DEFAULT 0,
    CONSTRAINT PK_SPECIAL_UNITS PRIMARY KEY (CIVILIZATION_ID, UNIT_ID),
    CONSTRAINT FK_SPECIAL_CIV FOREIGN KEY (CIVILIZATION_ID) REFERENCES CIVILIZATION_STATS (CIVILIZATION_ID),
    CONSTRAINT CHK_TYPE_SPECIAL CHECK (TYPE_UNIT IN ('Magician', 'Priest'))
);