-- 1. CREAR LA BASE DE DATOS (Si no existe)
CREATE DATABASE IF NOT EXISTS juego_civilizaciones;

-- 2. SELECCIONAR LA BASE DE DATOS (Esto soluciona el Error 1046)
USE juego_civilizaciones;

-- 3. TABLA DE ESTADO GENERAL
CREATE TABLE IF NOT EXISTS CIVILIZATION_STATS (
    CIVILIZATION_ID INT NOT NULL AUTO_INCREMENT, 
    NAME VARCHAR(50),
    WOOD_AMOUNT INT,
    IRON_AMOUNT INT,
    FOOD_AMOUNT INT,
    MANA_AMOUNT INT,
    MAGICTOWER_COUNTER INT DEFAULT 0,
    CHURCH_COUNTER INT DEFAULT 0,
    FARM_COUNTER INT DEFAULT 0,
    SMITHY_COUNTER INT DEFAULT 0,
    CARPENTRY_COUNTER INT DEFAULT 0,
    TECHNOLOGY_DEFENSE_LEVEL INT DEFAULT 0,
    TECHNOLOGY_ATTACK_LEVEL INT DEFAULT 0,
    BATTLES_COUNTER INT DEFAULT 0,
    CONSTRAINT PK_CIVILIZATION_STATS PRIMARY KEY (CIVILIZATION_ID)
);

-- 4. TABLA DE UNIDADES DE ATAQUE
CREATE TABLE IF NOT EXISTS ATTACK_UNITS_STATS (
    CIVILIZATION_ID INT NOT NULL,
    UNIT_ID INT NOT NULL,
    TYPE_UNIT VARCHAR(20),
    ARMOR INT,
    BASE_DAMAGE INT,
    EXPERIENCE INT DEFAULT 0,
    SANCTIFIED VARCHAR(3) DEFAULT 'NO',
    CONSTRAINT PK_ATTACK_UNITS PRIMARY KEY (CIVILIZATION_ID, UNIT_ID),
    CONSTRAINT FK_ATTACK_CIV FOREIGN KEY (CIVILIZATION_ID) REFERENCES CIVILIZATION_STATS (CIVILIZATION_ID),
    CONSTRAINT CHK_TYPE_ATTACK CHECK (TYPE_UNIT IN ('Swordsman', 'Spearman', 'Crossbow', 'Cannon'))
);

-- 5. TABLA DE UNIDADES DE DEFENSA
CREATE TABLE IF NOT EXISTS DEFENSE_UNITS_STATS (
    CIVILIZATION_ID INT NOT NULL,
    UNIT_ID INT NOT NULL,
    TYPE_UNIT VARCHAR(30),
    ARMOR INT,
    BASE_DAMAGE INT,
    EXPERIENCE INT DEFAULT 0,
    SANCTIFIED VARCHAR(3) DEFAULT 'NO',
    CONSTRAINT PK_DEFENSE_UNITS PRIMARY KEY (CIVILIZATION_ID, UNIT_ID),
    CONSTRAINT FK_DEFENSE_CIV FOREIGN KEY (CIVILIZATION_ID) REFERENCES CIVILIZATION_STATS (CIVILIZATION_ID),
    CONSTRAINT CHK_TYPE_DEFENSE CHECK (TYPE_UNIT IN ('Arrow Tower', 'Catapult', 'Rocket Launcher Tower'))
);

-- 6. TABLA DE UNIDADES ESPECIALES
CREATE TABLE IF NOT EXISTS SPECIAL_UNITS_STATS (
    CIVILIZATION_ID INT NOT NULL,
    UNIT_ID INT NOT NULL,
    TYPE_UNIT VARCHAR(20),
    ARMOR INT,
    BASE_DAMAGE INT,
    EXPERIENCE INT DEFAULT 0,
    CONSTRAINT PK_SPECIAL_UNITS PRIMARY KEY (CIVILIZATION_ID, UNIT_ID),
    CONSTRAINT FK_SPECIAL_CIV FOREIGN KEY (CIVILIZATION_ID) REFERENCES CIVILIZATION_STATS (CIVILIZATION_ID),
    CONSTRAINT CHK_TYPE_SPECIAL CHECK (TYPE_UNIT IN ('Magician', 'Priest'))
);